services:
  mcp-server-database:
    image: mcp-server-database
    container_name: mcp-server-database
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MCP_TOOLS_SPEC_LOCATION_PATTERN: "./tools/*.yml"
      DB_CONNECTIONS_CONFIG_PATH: "./configs"
    ports:
      - "${HOST_PORT:-11965}:${SERVER_PORT:-8080}"
    volumes:
      - ./configs:/app/configs
      - ./tmp:/app/tmp
    restart: unless-stopped
